### ISSUE TITLE
Errors with Angular 1.3

### ISSUE THREAD

**Issue by samaxes** [revolunet/angular-carousel#250]
When a `ngIf` directive resolves to `false` on a `rn-carousel` element, angular-carousel crashes with the following error in loop:

```
Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: [["fn: cspSafeGetter; newVal: -1; oldVal: 0"],["fn: cspSafeGetter; newVal: 0; oldVal: -1"],["fn: cspSafeGetter; newVal: -1; oldVal: 0"],["fn: cspSafeGetter; newVal: 0; oldVal: -1"],["fn: cspSafeGetter; newVal: -1; oldVal: 0"]]
http://errors.angularjs.org/1.3.2/$rootScope/infdig?p0=10&p1=%5B%5B%22fn%3A…5B%22fn%3A%20cspSafeGetter%3B%20newVal%3A%20-1%3B%20oldVal%3A%200%22%5D%5D
    at http://localhost:9000/bower_components/angular/angular.js:80:12
    at Scope.$digest (http://localhost:9000/bower_components/angular/angular.js:14080:19)
    at Scope.$apply (http://localhost:9000/bower_components/angular/angular.js:14304:24)
    at done (http://localhost:9000/bower_components/angular/angular.js:9518:47)
    at completeRequest (http://localhost:9000/bower_components/angular/angular.js:9703:7)
    at XMLHttpRequest.requestLoaded (http://localhost:9000/bower_components/angular/angular.js:9646:9) 
```

On line 537 of the dist file (`var oldSlides = (currentSlides || newValue).slice();`) we also need to check for `undefined` values:

```
TypeError: Cannot read property 'slice' of undefined
    at http://localhost:9000/bower_components/angular-carousel/dist/angular-carousel.js:537:76
    at Object.$watchCollectionAction [as fn] (http://localhost:9000/bower_components/angular/angular.js:13907:13)
    at Scope.$digest (http://localhost:9000/bower_components/angular/angular.js:14042:29)
    at Scope.$apply (http://localhost:9000/bower_components/angular/angular.js:14304:24)
    at done (http://localhost:9000/bower_components/angular/angular.js:9518:47)
    at completeRequest (http://localhost:9000/bower_components/angular/angular.js:9703:7)
    at XMLHttpRequest.requestLoaded (http://localhost:9000/bower_components/angular/angular.js:9646:9) 
```

**Comment by samaxes** [comment]
Hi @revolunet, have you had the time to look at this issue?

**Comment by albertpak** [comment]
Ran into same issue today - Angular 1.3.x

**Comment by judezhu** [comment]
I have second error as well. My version number is 1.2.28.

**Comment by matohawk** [comment]
Me too I have the same error, it's appear when we load in asynchrous the data like ajax call.
When I populate directly the slides with $scope.slides = {slide1, slide2 ...} I have no issue.

**Comment by nowink** [comment]
I have the same error. As matohawk said, i load the daata asynchronous.

**Comment by equus71** [comment]
We are using a#1.3.11. We had similar problem whenever the carousel were empty (including async data loading).
We have added ng-if="dataSetNotEmpty" above the rn-carousel and this solves the issue.

**Comment by saystone** [comment]
thanks. @equus71 it works!

**Comment by tonyawad88** [comment]
Thanks @equus71. It works, the error is gone.
